services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: eims_sqlserver
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=YourStrongPass#2024
    ports:
      - "1433:1433"
    volumes:
      - sql_data:/var/opt/mssql
      - ./sql/backup:/var/backups
      - ./sql/scripts:/var/scripts
    command: >
      /bin/bash -c "
      /opt/mssql/bin/sqlservr &
      sleep 30 &&
      /var/scripts/restore.sh
      "

volumes:
  sql_data: