version: "3.9"

services:
  postgres:
    image: postgres:16
    container_name: eims-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: eimsdb
      POSTGRES_USER: ghp
      POSTGRES_PASSWORD: "12345AsD,./"
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
