/* =====================================================================
   EIMS - Ticket module tables, DBeaver-safe.

   Replaces 2026-08-26_AddTicketModule_schema.sql, which was generated by
   "dotnet ef migrations script" and cannot run here for two reasons:

     1. GO is a sqlcmd/SSMS batch separator, not T-SQL. DBeaver sends it
        to the server verbatim and SQL Server answers
        "Incorrect syntax near 'GO'".

     2. It ends with an unguarded INSERT into __EFMigrationsHistory.
        Startup calls EnsureCreatedAsync(), not MigrateAsync(), so on a
        database created that way the table does not exist at all and the
        insert fails with "Invalid object name". The other scripts in this
        folder already guard that insert; this one did not.

   No GO. Idempotent - every object is created only if absent, so this is
   safe to re-run after a partial failure.

   >>> HOW TO RUN IN DBEAVER <<<
   Execute script (Alt+X). No DECLAREd variables cross statements here,
   so batch-splitting is harmless.
   ===================================================================== */

SET NOCOUNT ON;
SET QUOTED_IDENTIFIER ON;
SET ANSI_NULLS ON;

/* ---- 1. Tickets ----------------------------------------------------- */
IF OBJECT_ID('dbo.Tickets', 'U') IS NULL
BEGIN
    CREATE TABLE dbo.Tickets (
        Id                int            NOT NULL IDENTITY,
        Title             nvarchar(200)  NOT NULL,
        [Description]     nvarchar(max)  NOT NULL,
        RaiseDate         datetime2      NOT NULL,
        [Status]          int            NOT NULL,
        TicketType        int            NOT NULL,
        RaisedByUserId    nvarchar(450)  NULL,
        AssignedToUserId  nvarchar(450)  NULL,
        ClosedAt          datetime2      NULL,
        CreatedBy         nvarchar(max)  NULL,
        CreatedAt         datetime2      NOT NULL,
        EditedBy          nvarchar(max)  NULL,
        EditedAt          datetime2      NOT NULL,
        MACAddress        nvarchar(max)  NULL,
        CONSTRAINT PK_Tickets PRIMARY KEY (Id)
    );
    PRINT 'created dbo.Tickets';
END
ELSE PRINT 'ok      dbo.Tickets';

/* ---- 2. TicketAttachments ------------------------------------------- */
IF OBJECT_ID('dbo.TicketAttachments', 'U') IS NULL
BEGIN
    CREATE TABLE dbo.TicketAttachments (
        Id                int            NOT NULL IDENTITY,
        TicketId          int            NOT NULL,
        StoredFileName    nvarchar(260)  NOT NULL,
        OriginalFileName  nvarchar(260)  NOT NULL,
        ContentType       nvarchar(150)  NULL,
        FileSize          bigint         NOT NULL,
        CreatedBy         nvarchar(max)  NULL,
        CreatedAt         datetime2      NOT NULL,
        EditedBy          nvarchar(max)  NULL,
        EditedAt          datetime2      NOT NULL,
        MACAddress        nvarchar(max)  NULL,
        CONSTRAINT PK_TicketAttachments PRIMARY KEY (Id),
        CONSTRAINT FK_TicketAttachments_Tickets_TicketId
            FOREIGN KEY (TicketId) REFERENCES dbo.Tickets (Id) ON DELETE NO ACTION
    );
    PRINT 'created dbo.TicketAttachments';
END
ELSE PRINT 'ok      dbo.TicketAttachments';

/* ---- 3. TicketComments ---------------------------------------------- */
IF OBJECT_ID('dbo.TicketComments', 'U') IS NULL
BEGIN
    CREATE TABLE dbo.TicketComments (
        Id            int            NOT NULL IDENTITY,
        TicketId      int            NOT NULL,
        [Message]     nvarchar(max)  NOT NULL,
        IsSystemNote  bit            NOT NULL,
        CreatedBy     nvarchar(max)  NULL,
        CreatedAt     datetime2      NOT NULL,
        EditedBy      nvarchar(max)  NULL,
        EditedAt      datetime2      NOT NULL,
        MACAddress    nvarchar(max)  NULL,
        CONSTRAINT PK_TicketComments PRIMARY KEY (Id),
        CONSTRAINT FK_TicketComments_Tickets_TicketId
            FOREIGN KEY (TicketId) REFERENCES dbo.Tickets (Id) ON DELETE NO ACTION
    );
    PRINT 'created dbo.TicketComments';
END
ELSE PRINT 'ok      dbo.TicketComments';

/* ---- 4. Foreign-key indexes ----------------------------------------- */
IF OBJECT_ID('dbo.TicketAttachments', 'U') IS NOT NULL
   AND NOT EXISTS (SELECT 1 FROM sys.indexes
                   WHERE name = 'IX_TicketAttachments_TicketId'
                     AND object_id = OBJECT_ID('dbo.TicketAttachments'))
BEGIN
    CREATE INDEX IX_TicketAttachments_TicketId ON dbo.TicketAttachments (TicketId);
    PRINT 'created IX_TicketAttachments_TicketId';
END
ELSE PRINT 'ok      IX_TicketAttachments_TicketId';

IF OBJECT_ID('dbo.TicketComments', 'U') IS NOT NULL
   AND NOT EXISTS (SELECT 1 FROM sys.indexes
                   WHERE name = 'IX_TicketComments_TicketId'
                     AND object_id = OBJECT_ID('dbo.TicketComments'))
BEGIN
    CREATE INDEX IX_TicketComments_TicketId ON dbo.TicketComments (TicketId);
    PRINT 'created IX_TicketComments_TicketId';
END
ELSE PRINT 'ok      IX_TicketComments_TicketId';

/* ---- 5. Migration bookkeeping, only if the table is even there ------- */
/*  Harmless either way: it just stops a future "dotnet ef database
    update" from trying to create these tables a second time.           */
IF OBJECT_ID('dbo.__EFMigrationsHistory', 'U') IS NOT NULL
   AND NOT EXISTS (SELECT 1 FROM dbo.__EFMigrationsHistory
                   WHERE MigrationId = N'20260826160955_AddTicketModule')
BEGIN
    INSERT INTO dbo.__EFMigrationsHistory (MigrationId, ProductVersion)
    VALUES (N'20260826160955_AddTicketModule', N'7.0.11');
    PRINT 'recorded migration in __EFMigrationsHistory';
END
ELSE PRINT 'ok      __EFMigrationsHistory';

/* ---- 6. Verify ------------------------------------------------------ */
SELECT
    Item   = v.Item,
    Status = CASE WHEN OBJECT_ID(v.TableName, 'U') IS NULL THEN 'MISSING' ELSE 'OK' END
FROM (VALUES
    ('Tickets',           'dbo.Tickets'),
    ('TicketComments',    'dbo.TicketComments'),
    ('TicketAttachments', 'dbo.TicketAttachments')
) AS v(Item, TableName);
